version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: cryptomath-auth-postgres
    restart: always
    env_file:
      - ./configs/database/config.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: cryptomath-auth-redis
    ports:
      - '6379:6379'
volumes:
  pgdata: